version: '3.8'
services:
  app:
    image: openai-demo-app
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
        - .:/Coursphere
        - /Coursphere/node_modules
        - /Coursphere/.next
    ports:
      - "3000:3000"